// Date: 2013.08.16 16:54:47
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package oldworldindustry.common.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelAxle extends ModelBase
{
  //fields
    ModelRenderer body1;
    ModelRenderer body2;
    ModelRenderer Gear1;
    ModelRenderer Gear2;
    ModelRenderer Gear2_1;
    ModelRenderer Gear1_1;
  
  public ModelAxle()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      body1 = new ModelRenderer(this, 0, 0);
      body1.addBox(-5F, 0.3F, 0F, 10, 1, 1);
      body1.setRotationPoint(0F, 0F, 0F);
      body1.setTextureSize(64, 32);
      body1.mirror = true;
      setRotation(body1, 0.7853982F, 0F, 0F);
      body2 = new ModelRenderer(this, 0, 3);
      body2.addBox(-5F, -0.3F, 0.4F, 10, 1, 1);
      body2.setRotationPoint(0F, 0F, 0F);
      body2.setTextureSize(64, 32);
      body2.mirror = true;
      setRotation(body2, 0F, 0F, 0F);
      Gear1 = new ModelRenderer(this, 7, 10);
      Gear1.addBox(0F, 0F, 0F, 1, 2, 2);
      Gear1.setRotationPoint(4F, 0.2F, -0.5F);
      Gear1.setTextureSize(64, 32);
      Gear1.mirror = true;
      setRotation(Gear1, 0.7853982F, 0F, 0F);
      Gear2 = new ModelRenderer(this, 7, 6);
      Gear2.addBox(0F, 0F, 0F, 1, 2, 2);
      Gear2.setRotationPoint(4F, -0.8F, -0.1F);
      Gear2.setTextureSize(64, 32);
      Gear2.mirror = true;
      setRotation(Gear2, 0F, 0F, 0F);
      Gear2_1 = new ModelRenderer(this, 0, 10);
      Gear2_1.addBox(0F, 0F, 0F, 1, 2, 2);
      Gear2_1.setRotationPoint(-5F, -0.8F, -0.1F);
      Gear2_1.setTextureSize(64, 32);
      Gear2_1.mirror = true;
      setRotation(Gear2_1, 0F, 0F, 0F);
      Gear1_1 = new ModelRenderer(this, 0, 6);
      Gear1_1.addBox(0F, 0F, 0F, 1, 2, 2);
      Gear1_1.setRotationPoint(-5F, 0.2F, -0.5F);
      Gear1_1.setTextureSize(64, 32);
      Gear1_1.mirror = true;
      setRotation(Gear1_1, 0.7853982F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    body1.render(f5);
    body2.render(f5);
    Gear1.render(f5);
    Gear2.render(f5);
    Gear2_1.render(f5);
    Gear1_1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
